### PR TITLE
Fix appending pointers when on 64-bit machine where long is 4 

### LINKED ISSUE #23: Feature request: native Windows support
I have a Windows-only project that dmalloc could really help with. Currently, it seems that the only way to use dmalloc on Windows is to build it with Cygwin, since the only virtual memory APIs that dmalloc currently speaks are `sbrk` and `mmap`, and Windows has neither.

If you are interested in this, I could prepare a pull request modifying `heap.c` to use `VirtualAlloc` / `VirtualFree` in addition to `mmap` / `munmap`, bringing me closer to my goal of cross-compiling dmalloc for Windows using something like `./configure --build=i686-linux-gnu --host=i686-w64-mingw32`. While lack of `mmap` could be worked around using `INTERNAL_MEMORY_SPACE`, it's not a good solution.

### PR DESCRIPTION
**Pull request by j256**
Fixes #23 .  Thanks much to @aitap .

### CODE REVIEW

**Comment by j256** [comment]
Does this fix anything @aitap ?

**Comment by aitap** [comment]
Unfortunately, I have to take cross-compiling into account in order to finish `./configure`. Are we allowed to use C99 types? With the following patch most of the warnings are gone:

```diff
diff --git a/configure.ac b/configure.ac
index 56b350c..8ec2096 100644
--- a/configure.ac
+++ b/configure.ac
@@ -444,7 +444,8 @@ else
 int main() { if (sizeof(long long)==8) return 0; else return 1; }
 ])],
        [ ac_cv_pnt_arith_type="long long" ],
-       [ ac_cv_pnt_arith_type="unsigned long" ])
+       [ ac_cv_pnt_arith_type="unsigned long" ],
+       [ ac_cv_pnt_arith_type="uintptr_t" ])
 fi
 AC_DEFINE_UNQUOTED([PNT_ARITH_TYPE],[$ac_cv_pnt_arith_type])
 AC_MSG_RESULT([$ac_cv_pnt_arith_type])
```

Strictly speaking, this requires me to include `<stdint.h>` somewhere, but something in the C library includes it already.

**Comment by j256** [comment]
`long long` doesn't work with cross compiling?

**Comment by aitap** [comment]
The third option to `AC_RUN_IFELSE` is needed in order to `./configure` when cross-compiling, and `uintptr_t` is the only safe option if runtime tests cannot be run.

**Comment by j256** [comment]
`long long` doesn't work?  What is `uintptr_t` actually set to?

**Comment by aitap** [comment]
When cross-compiling, runtime tests are unavailable, because `./configure` stops the process instead of trying to run `./conftest.exe` on Linux (or ARM Linux `./conftest` on X86-64 Linux, despite it _could_ be possible with wine or qemu, respectively).

`uintptr_t` is `typedef`-ed by the standard library to different things on different platforms: `unsigned long` or `unsigned int` depending on gcc-specific `__WORDSIZE` in glibc; `long long unsigned int` or `unsigned int` in mingw.

**Comment by j256** [comment]
Sorry, I don't have experience with cross compiling in case you couldn't tell but I get it now.  That's why you needed the 3rd arg in the getpagesize calcs.  Hrm.  How about using `AC_CHECK_SIZEOF(long long)` does that work with cross compiling?

**Comment by aitap** [comment]
Yes, `AC_CHECK_SIZEOF` works when cross-compiling since 2007.

**Comment by j256** [comment]
I pushed a change to configure to support checking long long against long.  Can you try it out?

**Comment by aitap** [comment]
Thanks again! I can confirm that `./configure` runs successfully for both 32-bit and 64-bit mingw. Casting 64-bit integers to 32-bit pointers will probably give us warnings, but at least no truncation is going to happen.

**Pull request merged**
